name: Deploy

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Add SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ls -la private_key  # Verificação se o arquivo foi criado corretamente

      - name: Deploy to Remote Server (EC2)
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} "
            cd /home/ubuntu/RecoopeCompose 
            ./deploy.sh "
